// end: 9

/**
 * @module
 */

/**
 * List of all internal NewSync commands IDs
 * @enum {number}
 */
export const COMMANDS = {
  // CLIENT SIDE COMMANDS:
  SUBSCRIBE_CONTAINER: 8,
  SUBSCRIBE_CONTAINERS: 2,
  SUBSCRIBE_ALL: 6,
  UNSUBSCRIBE_CONTAINER: 9,
  UNSUBSCRIBE_CONTAINERS: 3,
  UNSUBSCRIBE_ALL: 7,

  // SERVE SIDE COMMANDS:
  NEW_CONTAINER: 4,
  NEW_CONTAINERS: 5,

  // SHARED COMMANDS:
  PING: 0,
  CONSOLE_LOG: 1,
}
