export const COMMANDS = {
  SUBSCRIBE: 0,
  UNSUBSCRIBE: 1,
  SUBSCRIBE_CONTAINER: 8,
  SUBSCRIBE_CONTAINERS: 2,
  SUBSCRIBE_ALL: 6,
  UNSUBSCRIBE_CONTAINER: 9,
  UNSUBSCRIBE_CONTAINERS: 3,
  UNSUBSCRIBE_ALL: 7,

  NEW_CONTAINER: 4,
  NEW_CONTAINERS: 5,
}
